### ISSUE TITLE
Een gebruiker moet kunnen registreren

### ISSUE THREAD

**Issue by mikevanl** [mikevanl/FireSale#13]
- [x] Er is een UI beschikbaar met een formulier om je als gebruiker te registreren
 - [x] Er is altijd een knop beschikbaar om jezelf te registreren totdat je bent ingelogd
 - [x] Er is een endpoint op de server waar een Post request op wordt afgehandeld

**Comment by Astrid-HR** [comment]
Ik pak taak 'Er is een UI beschikbaar met een formulier om je als gebruiker te registreren' op
