### ISSUE TITLE
Entiteiten

### ISSUE THREAD

**Issue by mikevanl** [mikevanl/FireSale#14]
De volgende entiteiten zijn aangemaakt

 - [x] BaseEntity
 - [x] User 
 - [x] Role 
 - [x] Claim 
 - [x] AuthToken 
 - [x] Auction 
 - [x] AuctionStatus 
 - [x] Image 
 - [x] Bid 
 - [x] Review 
- [x] Tag
- [x] Category

**Comment by carloligthart** [comment]
@mikevanl @JimGeersinga Kunnen jullie deze reviewen? @0548643 gaan verder met de ERD zodra nadat de entiteiten gereviewed zijn
