### ISSUE TITLE
Plan van aanpak

### ISSUE THREAD

**Issue by mikevanl** [mikevanl/FireSale#20]

**Comment by Astrid-HR** [comment]
Ik heb zojuist het PvA wat gefinetuned, wat afgehandelde opmerkingen op afgehandeld gezet en nog een vraag toegevoegd. Tevens #43  toegevoegd aam het PvA..

**Comment by carloligthart** [comment]
Requirements toegevoegd/bewerkt/verwijderd obv feedback van Dion van 23 nov
