### ISSUE TITLE
Class diagram / ERD / UML

### ISSUE THREAD

**Issue by mikevanl** [mikevanl/FireSale#35]
[WIP](https://drive.google.com/file/d/1W3OqukVYZE9egfWp9i8mDLqscKjFzE-R/view?usp=sharing)

**Comment by carloligthart** [comment]
Work in progress [linkje](https://drive.google.com/file/d/1W3OqukVYZE9egfWp9i8mDLqscKjFzE-R/view?usp=sharing)

Staat ook in Google Drive
